version: 2
jobs:
  build:
    working_directory: ~/asynchronizer
    docker:
      - image: hseeberger/scala-sbt:graalvm
    environment:
      - SBT_VERSION: 1.4.0
      - CODECOV_TOKEN: "7662c218-08d5-4137-9a27-d97c7a1a5194"
    steps:
      - run: echo 'export ARTIFACT_BUILD=$CIRCLE_PROJECT_REPONAME-$CIRCLE_BUILD_NUM.zip ' >> $BASH_ENV
      - run: echo 'export SBT_OPTS="-XX:MaxMetaspaceSize=512m -Xms1024m -Xmx1024m" ' >> $BASH_ENV
      - checkout
      - run:
          name: Compile & Test ASYNCHRONIZER
          command: cat /dev/null | sbt +clean +compile coverage test run coverageReport
      - run:
          name: Push Coverage Report to Codecov Dashboard
          command: bash <(curl -s https://codecov.io/bash)
      - store_test_results:
          path: target/test-reports

